### ISSUE TITLE
Twisted client documentation

### ISSUE THREAD

**Issue by jukeks** [depop/txstatsd#1]
I'm having hard time figuring out how initialize the twisted client. I noticed example-stats-client.tac has not been updated to use TwistedStatsDClient.create.  

Does the client need any other initialization than the code below?

```
statsd_client = TwistedStatsDClient.create(address, host)
reactor.listenUDP(0, StatsDClientProtocol(statsd_client))
```

**Comment by anentropic** [comment]
report all general issues to the parent repo, not to our fork

see
https://github.com/sidnei/txstatsd
